<h1>This is template from Faq module</h1>
<?php /** @var $block \Magefan\Faq\Block\Faq */ ?>
<!-- Call block function -->
<?php $a = $block->getFaqItem();?>
    <?php if (!is_string($a)) {   ?>
   <h3><?php  echo  $a->getData('question')?></h3></br>
    <h4><?php echo $a->getData('answer');  } else { ?></h4></br>
    <h1><?php echo $a; }?></h1>


  <?php /** $viewModel = $block->getViewModel(); */ ?>
  <?php /** echo $block->escapeHtml($viewModel->display()); */ ?>